"""GitHub Integration for PR creation and repository operations"""
import os
import base64
from typing import Dict, List, Optional
from datetime import datetime
try:
    from github import Github
except ImportError:
    Github = None
from src.utils.logger import get_logger

logger = get_logger(__name__)

class GitHubIntegration:
    def __init__(self, token: Optional[str] = None):
        self.token = token or os.getenv("GITHUB_TOKEN")
        if not self.token:
            raise ValueError("GitHub token not provided")
        self.client = Github(self.token) if Github else None

    def get_repo(self, repo_full_name: str):
        if self.client:
            return self.client.get_repo(repo_full_name)
        return None

    def create_fix_branch(self, repo_name: str, base_branch: str = "main") -> str:
        repo = self.get_repo(repo_name)
        if not repo:
            return ""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        branch_name = f"sre-fix-{timestamp}"
        try:
            base_ref = repo.get_git_ref(f"heads/{base_branch}")
            repo.create_git_ref(f"refs/heads/{branch_name}", base_ref.object.sha)
            logger.info(f"Created branch {branch_name}")
            return branch_name
        except Exception as e:
            logger.error(f"Failed to create branch: {e}")
            return ""

    def commit_file_changes(self, repo_name: str, branch: str,
                           file_changes: List[Dict], commit_message: str) -> bool:
        repo = self.get_repo(repo_name)
        if not repo:
            return False
        try:
            ref = repo.get_git_ref(f"heads/{branch}")
            latest_commit = repo.get_git_commit(ref.object.sha)
            base_tree = repo.get_git_tree(latest_commit.tree.sha)
            new_tree_elements = []
            for change in file_changes:
                blob = repo.create_git_blob(change["content"], "utf-8")
                new_tree_elements.append({
                    "path": change["path"],
                    "mode": "100644",
                    "type": "blob",
                    "sha": blob.sha
                })
            new_tree = repo.create_git_tree(new_tree_elements, base_tree)
            new_commit = repo.create_git_commit(
                message=commit_message,
                tree=new_tree,
                parents=[latest_commit]
            )
            ref.edit(new_commit.sha)
            logger.info(f"Committed {len(file_changes)} files to {branch}")
            return True
        except Exception as e:
            logger.error(f"Failed to commit: {e}")
            return False

    def create_pull_request(self, repo_name: str, branch: str,
                           title: str, body: str, base: str = "main") -> Optional[Dict]:
        repo = self.get_repo(repo_name)
        if not repo:
            return None
        try:
            pr = repo.create_pull(title=title, body=body, head=branch, base=base)
            logger.info(f"Created PR #{pr.number}: {pr.html_url}")
            return {
                "number": pr.number,
                "url": pr.html_url,
                "title": pr.title,
                "branch": branch,
                "state": pr.state
            }
        except Exception as e:
            logger.error(f"Failed to create PR: {e}")
            return None

    def generate_pr_description(self, root_cause: Dict, fixes: List[Dict],
                                 test_results: Optional[Dict] = None) -> str:
        body = f"""## AI DevOps SRE - Automated Fix

### Root Cause Analysis
**Category:** {root_cause.get('category', 'Unknown')}
**Severity:** {root_cause.get('severity', 'Unknown')}
**Confidence:** {root_cause.get('confidence', 'N/A')}

### Description
{root_cause.get('description', 'No description available')}

### Evidence
"""
        for evidence in root_cause.get('evidence', []):
            body += f"- {evidence}\n"
        body += "\n### Changes Made\n"
        for fix in fixes:
            body += f"- **{fix.get('file', 'Unknown')}**: {fix.get('description', 'Fix applied')}\n"
        if test_results:
            body += f"\n### Test Results\n- Status: {test_results.get('status', 'Unknown')}\n"
        body += "\n---\n*This PR was automatically generated by AI DevOps SRE*"
        return body

    def get_file_content(self, repo_name: str, file_path: str, ref: str = "main") -> Optional[str]:
        repo = self.get_repo(repo_name)
        if not repo:
            return None
        try:
            content = repo.get_contents(file_path, ref=ref)
            if isinstance(content, list):
                return None
            return base64.b64decode(content.content).decode('utf-8')
        except Exception as e:
            logger.error(f"Failed to get file: {e}")
            return None